# Generated by Django 5.1 on 2024-09-06 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0002_spotifytoken_guest_id_alter_spotifytoken_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spotifytoken',
            name='guest_id',
        ),
    ]
