# Generated by Django 5.1 on 2024-09-06 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0003_remove_spotifytoken_guest_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotifytoken',
            name='guest_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
