# Generated by Django 5.1 on 2024-09-06 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0004_spotifytoken_guest_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotifytoken',
            name='guest_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
