# Generated by Django 5.1 on 2024-09-06 02:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0005_alter_spotifytoken_guest_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotifytoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 6, 2, 35, 52, 627157, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
