# Generated by Django 5.1 on 2024-08-30 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_feedback_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='page_url',
            field=models.URLField(blank=True),
        ),
    ]
