# Generated by Django 5.1 on 2024-08-26 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('desc_long', models.TextField(blank=True, null=True)),
                ('room', models.CharField(max_length=255)),
                ('requires_batteries', models.BooleanField(default=False)),
                ('battery_type', models.CharField(blank=True, max_length=50, null=True)),
                ('number_of_batteries', models.IntegerField(blank=True, null=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='items/')),
            ],
        ),
    ]
