name: Build and Push to GHCR

on:
  push:
    branches: [ "*" ]  # or any other branches you want to build on
  # You can also add tags: [ "*" ] for building on any git tag.

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    
    steps:
      # 1. Check out the repo code
      - name: Check out code
        uses: actions/checkout@v3

      # 2. Log in to GitHub Container Registry (GHCR)
      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 3. Build and push the Docker image
      - name: Build and Push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}BlackDiamondHub:latest


